name: CI Debug

on:
  push:
    branches: [ '**' ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show env
        run: |
          echo "Running on $RUNNER_OS"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "List current directory:" && ls -la
